#
# $ conda env create -f spot_conda_environment.yml
# then,
# $ conda activate spot
# $ pip install .
#
name: spot
dependencies:
  - python=3.13
  - astropy>=7.2.1
  - scipy
  - matplotlib>=3.8
  - pillow>=12.3.0
  - pyqt
  - qtpy
  - python-dateutil
  - pyyaml
  - pip
  - pip:
    - ginga>=7.2.0


