#! /usr/bin/env python
#
# spot -- Site Planning and Observation Tool
#
import sys
import os
from argparse import ArgumentParser

if 'CONFHOME' in os.environ:
    spot_home = os.path.join(os.environ['CONFHOME'], 'spot')
else:
    spot_home = os.path.join(os.path.expanduser('~'), '.spot')

from ginga.util import paths
paths.set_home(spot_home)

import spot.version as version
from spot.main import SPOT, default_layout


if __name__ == "__main__":

    # construct viewer builder
    viewer = SPOT(layout=default_layout, appname='spot', channels=[],
                  basedir=spot_home)
    viewer.add_separately_distributed_plugins()

    argprs = ArgumentParser(description="Site Planning and Observation Tool")
    viewer.add_default_options(argprs)
    argprs.add_argument('-V', '--version', action='version',
                        version='%(prog)s {}'.format(version.version))

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    viewer.main(options, args)
